language: java
jdk: 
 - oraclejdk7
 - oraclejdk8
 - openjdk7

matrix:

# sudo: required


before_script:
  - echo "MAVEN_OPTS='-Xmx2g -XX:MaxPermSize=512m'" > ~/.mavenrc
install:
  - 
#build
script:
  - mvn install
  - mvn site
  
